# Generated by Django 4.2.13 on 2024-06-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meter_serial', models.CharField(max_length=20)),
                ('channel', models.IntegerField(choices=[(1, '1.8.0'), (2, '2.8.0')])),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('s', 'Fernauslesung'), ('m', 'Manuell'), ('e', 'Geschätzt'), ('i', 'Ungültig')], db_index=True, default='s', max_length=1)),
                ('reading_reason', models.CharField(blank=True, choices=[('installation_reading', 'Einbauzählerstand'), ('deinstallation_reading', 'Ausbauzählerstand'), ('midway_reading', 'Zwischenablesung'), ('contract_start', 'MaKo Wechsel Stilllegung'), ('contract_end', 'MaKo Wechsel Drittbelieferung')], max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Datenpunkt',
                'verbose_name_plural': 'Datenpunkte',
                'indexes': [models.Index(fields=['meter_serial', 'timestamp'], name='meter_data__meter_s_2a7308_idx'), models.Index(fields=['channel', 'meter_serial', 'timestamp'], name='meter_data__channel_542a26_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='data',
            constraint=models.UniqueConstraint(fields=('channel', 'meter_serial', 'timestamp', 'source'), name='unique_channel_meter_timestamp_source'),
        ),
    ]
